# Generated by Django 2.2.4 on 2019-08-17 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_builder', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BoatClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_class', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BoatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BoatUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_use', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enumerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_name', models.CharField(max_length=200)),
                ('other_name', models.CharField(max_length=200)),
                ('tel1', models.CharField(max_length=200)),
                ('tel2', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HullMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hull_material', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LandingSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat_census.District')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=200)),
                ('driver_license', models.CharField(max_length=200)),
                ('tel1', models.CharField(max_length=200)),
                ('tel2', models.CharField(max_length=200)),
                ('tel3', models.CharField(max_length=200)),
                ('tel4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Propulsion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_number', models.CharField(max_length=200)),
                ('vessel_name', models.CharField(max_length=200)),
                ('life_jackets', models.IntegerField()),
                ('life_rings', models.IntegerField()),
                ('passenger_capacity', models.IntegerField()),
                ('cargo_capacity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hull_id', models.CharField(max_length=200)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('year_of_build', models.CharField(max_length=4, null=True)),
                ('census_date', models.DateField(null=True)),
                ('boat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat_census.BoatClass')),
                ('boat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boat_census.BoatType')),
                ('boat_use', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boat_census.BoatUse')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat_census.District')),
                ('entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enumerator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boat_census.Enumerator')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boat_census.FuelType')),
                ('hull_color', models.ManyToManyField(to='boat_census.Color')),
                ('hull_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boat_census.HullMaterial')),
                ('landing_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat_census.LandingSite')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boat_census.Owner')),
                ('propulsion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boat_census.Propulsion')),
            ],
        ),
    ]
