# Generated by Django 2.2.4 on 2019-08-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_census', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='driver_license',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='owner',
            name='national_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='owner',
            name='tel1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='owner',
            name='tel2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='owner',
            name='tel3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='owner',
            name='tel4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
