# Generated by Django 2.2.4 on 2019-08-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat_census', '0002_auto_20190817_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='district',
        ),
    ]
