# Generated by Django 2.2.4 on 2019-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_census', '0003_remove_vessel_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='cabin_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
