# Generated by Django 2.2.4 on 2019-08-22 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boat_census', '0005_auto_20190822_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='cabin_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabincolor', to='boat_census.Color'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='hull_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hullcolor', to='boat_census.Color'),
        ),
    ]
