# Generated by Django 2.2.4 on 2019-08-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat_census', '0006_auto_20190823_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='cabin_color',
        ),
    ]
